### ISSUE TITLE
Unable to show window in Windows 10

### ISSUE THREAD

**Issue by talk2sunil83** [YetAnotherPomodoroApp/YAPA-2#43]
When I try to run the application it does not load, after investigation i found below exception is being thrown, 

System.Windows.Data Error: 1 : Cannot create default converter to perform 'one-way' conversions between types 'System.Windows.Media.Color' and 'System.Windows.Media.Brush'. Consider using Converter property of Binding. BindingExpression:Path=TextShadowColor; DataItem='YapaTheme' (Name=''); target element is 'TextBlock' (Name=''); target property is 'Background' (type 'Brush')
System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='#FFFFFAFA' BindingExpression:Path=TextShadowColor; DataItem='YapaTheme' (Name=''); target element is 'TextBlock' (Name=''); target property is 'Background' (type 'Brush')
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.FormatException' in System.dll
System.Windows.Data Error: 6 : 'TargetDefaultValueConverter' converter failed to convert value '' (type 'String'); fallback value will be used, if available. BindingExpression:Path=ProgressState; DataItem='YapaTheme' (Name=''); target element is 'TaskbarItemInfo' (HashCode=26673201); target property is 'ProgressState' (type 'TaskbarItemProgressState') FormatException:'System.FormatException:  is not a valid value for TaskbarItemProgressState. ---> System.ArgumentException: Must specify valid information for parsing in the string.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.TargetDefaultValueConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'

Thanks

**Comment by floatas** [comment]
Thank you for reporting an issue, from this stack trace it's more or less impossible to identify what is causing this issue. I will need more information, does this issue still happen ?
